name: Update tag

on:
  push:
    branches: [ fdroid ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Update git tag
      run: |
        git tag -f f-droid
        git push -f origin f-droid
